name: Packer Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  format-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.6/packer_1.7.6_linux_amd64.zip
          unzip packer_1.7.6_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Check Packer format
        run: |
          packer fmt -check packer.pkr.hcl
          
      - name: Build Flask application artifact
        run: |
            zip -r webapp.zip ./

      - name: Validate Packer template
        run: |
          packer init .
          packer validate packer.pkr.hcl
